# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: valveextensions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='valveextensions.proto',
  package='dota',
  syntax='proto2',
  serialized_options=b'H\001\200\001\000',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15valveextensions.proto\x12\x04\x64ota\x1a google/protobuf/descriptor.proto:9\n\tmap_field\x12\x1d.google.protobuf.FieldOptions\x18\xc8\xdc\x03 \x01(\x08:\x05\x66\x61lse:7\n\x07map_key\x12\x1d.google.protobuf.FieldOptions\x18\xc9\xdc\x03 \x01(\x08:\x05\x66\x61lse:=\n\x11\x64iff_encode_field\x12\x1d.google.protobuf.FieldOptions\x18\xca\xdc\x03 \x01(\x05:\x01\x30:<\n\x0c\x64\x65lta_ignore\x12\x1d.google.protobuf.FieldOptions\x18\xcb\xdc\x03 \x01(\x08:\x05\x66\x61lse:?\n\x13steamml_max_entries\x12\x1d.google.protobuf.FieldOptions\x18\xcc\xdc\x03 \x01(\r:\x01\x30:D\n\x14steamml_is_timestamp\x12\x1d.google.protobuf.FieldOptions\x18\xcd\xdc\x03 \x01(\x08:\x05\x66\x61lse:<\n\x10steamlearn_count\x12\x1d.google.protobuf.FieldOptions\x18\xce\xdc\x03 \x01(\r:\x01\x30:@\n\x14schema_friendly_name\x12!.google.protobuf.EnumValueOptions\x18\xe8\x07 \x01(\t:>\n\x12schema_description\x12!.google.protobuf.EnumValueOptions\x18\xe9\x07 \x01(\t:F\n\x1aschema_suppress_enumerator\x12!.google.protobuf.EnumValueOptions\x18\xea\x07 \x01(\x08\x42\x05H\x01\x80\x01\x00'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


MAP_FIELD_FIELD_NUMBER = 61000
map_field = _descriptor.FieldDescriptor(
  name='map_field', full_name='dota.map_field', index=0,
  number=61000, type=8, cpp_type=7, label=1,
  has_default_value=True, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
MAP_KEY_FIELD_NUMBER = 61001
map_key = _descriptor.FieldDescriptor(
  name='map_key', full_name='dota.map_key', index=1,
  number=61001, type=8, cpp_type=7, label=1,
  has_default_value=True, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
DIFF_ENCODE_FIELD_FIELD_NUMBER = 61002
diff_encode_field = _descriptor.FieldDescriptor(
  name='diff_encode_field', full_name='dota.diff_encode_field', index=2,
  number=61002, type=5, cpp_type=1, label=1,
  has_default_value=True, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
DELTA_IGNORE_FIELD_NUMBER = 61003
delta_ignore = _descriptor.FieldDescriptor(
  name='delta_ignore', full_name='dota.delta_ignore', index=3,
  number=61003, type=8, cpp_type=7, label=1,
  has_default_value=True, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
STEAMML_MAX_ENTRIES_FIELD_NUMBER = 61004
steamml_max_entries = _descriptor.FieldDescriptor(
  name='steamml_max_entries', full_name='dota.steamml_max_entries', index=4,
  number=61004, type=13, cpp_type=3, label=1,
  has_default_value=True, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
STEAMML_IS_TIMESTAMP_FIELD_NUMBER = 61005
steamml_is_timestamp = _descriptor.FieldDescriptor(
  name='steamml_is_timestamp', full_name='dota.steamml_is_timestamp', index=5,
  number=61005, type=8, cpp_type=7, label=1,
  has_default_value=True, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
STEAMLEARN_COUNT_FIELD_NUMBER = 61006
steamlearn_count = _descriptor.FieldDescriptor(
  name='steamlearn_count', full_name='dota.steamlearn_count', index=6,
  number=61006, type=13, cpp_type=3, label=1,
  has_default_value=True, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
SCHEMA_FRIENDLY_NAME_FIELD_NUMBER = 1000
schema_friendly_name = _descriptor.FieldDescriptor(
  name='schema_friendly_name', full_name='dota.schema_friendly_name', index=7,
  number=1000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
SCHEMA_DESCRIPTION_FIELD_NUMBER = 1001
schema_description = _descriptor.FieldDescriptor(
  name='schema_description', full_name='dota.schema_description', index=8,
  number=1001, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
SCHEMA_SUPPRESS_ENUMERATOR_FIELD_NUMBER = 1002
schema_suppress_enumerator = _descriptor.FieldDescriptor(
  name='schema_suppress_enumerator', full_name='dota.schema_suppress_enumerator', index=9,
  number=1002, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.extensions_by_name['map_field'] = map_field
DESCRIPTOR.extensions_by_name['map_key'] = map_key
DESCRIPTOR.extensions_by_name['diff_encode_field'] = diff_encode_field
DESCRIPTOR.extensions_by_name['delta_ignore'] = delta_ignore
DESCRIPTOR.extensions_by_name['steamml_max_entries'] = steamml_max_entries
DESCRIPTOR.extensions_by_name['steamml_is_timestamp'] = steamml_is_timestamp
DESCRIPTOR.extensions_by_name['steamlearn_count'] = steamlearn_count
DESCRIPTOR.extensions_by_name['schema_friendly_name'] = schema_friendly_name
DESCRIPTOR.extensions_by_name['schema_description'] = schema_description
DESCRIPTOR.extensions_by_name['schema_suppress_enumerator'] = schema_suppress_enumerator
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(map_field)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(map_key)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(diff_encode_field)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(delta_ignore)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(steamml_max_entries)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(steamml_is_timestamp)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(steamlearn_count)
google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(schema_friendly_name)
google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(schema_description)
google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(schema_suppress_enumerator)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
